name: Packer Custom Image Build and Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Install Packer
        uses: hashicorp/setup-packer@v1
        with:
          version: '1.9.4'

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: "21"
          distribution: "adopt"

      # Rest of your workflow remains the same
      - name: Build with Maven
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: mvn clean install -DskipTests

      - name: Run tests
        run: mvn test

      - name: Build Packer Image
        working-directory: PKR
        env:
          PACKER_LOG: 1
        run: |
          packer init .
          packer validate -var="aws_region=${{secrets.AWS_REGION}}" \
            -var="subnet_id=${{secrets.SUBNET_ID}}" \
            -var='ami_users=["${{secrets.AMI_USERS}}"]' \
            .
          packer build -var="aws_region=${{secrets.AWS_REGION}}" \
            -var="subnet_id=${{secrets.SUBNET_ID}}" \
            -var='ami_users=["${{secrets.AMI_USERS}}"]' \
            .
          AMI_ID=$(aws ec2 describe-images --filters "Name=name,Values=csye6225_*" --query 'sort_by(Images, &CreationDate)[-1].ImageId' --output text)
          echo "AMI_ID=${AMI_ID}" >> $GITHUB_ENV

      # Rest of your workflow remains the same...
